<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title><?php echo htmlentities ($this->title) ?></title>
<style>
body
{
    margin: 0;
    padding: 0;
    background-color: #000; 
    color: #ff0; 
    font-family: "Lucida Console", Monaco, "Courier New", Courier, monospace; 
    font-size: 90%; 
}
.console
{
  white-space: pre;
  display: block;
}
</style>
</head>
<body>
<div class="console"><?php echo $this->output; ?></div>
</body>
</html>
