<?php
$api = $this->app->config->api('url');
$cdn = $this->app->config->web('cdn');
?>
<html>
<head>
<title><?php echo htmlentities ($this->title) ?></title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $cdn ?>/css/qtip/jquery.qtip.min.css">
<script type="text/javascript" src="<?php echo $cdn ?>/js/qtip2/jquery.qtip.min.js"></script>
<style>
body 
{ 
    background-color: #000; 
    color: #ff0; 
    font-family: "Lucida Console", Monaco, "Courier New", Courier, monospace; 
    font-size: 90%; 
}
.console
{
  white-space: pre;
  display: block;
}
a:link {color:#ff0;}
a:visited {color:#ff0;}
a:hover {color:#ff0;}
a:active {color:#ff0;}

.facebook_profile a:link {color:#000;}
.facebook_profile a:visited {color:#ff0;}
.facebook_profile a:hover {color:#ff0;}
.facebook_profile a:active {color:#ff0;}

.qtip-user{
    max-width: 385px;
}

.qtip-user p{
    margin: 0 0 6px;
}

.qtip-user h1{
    font-size: 20px;
    line-height: 1.1;
    margin: 0 0 5px;
}

.qtip-user img{
    float: left;
    margin: 10px 10px 10px 0;
}

.qtip-user .info{
    overflow: hidden;
}

.qtip-user p.note{
    font-weight: 700;
}
</style>
</head>
<body>
<div class="console"><?php echo $this->output; ?></div>
<script>
 $(document).ready(function()
 {
     // MAKE SURE YOUR SELECTOR MATCHES SOMETHING IN YOUR HTML!!!
     $('a').each(function() {
         $(this).qtip({
            content: {
                text: function(event, api) {
                    $.ajax({
                        url: '<?php echo $api ?>/facebook/' + api.elements.target.attr('title')
                    })
                    .then(function(content) {
                        // Set the tooltip content upon successful retrieval
                        api.set('content.text', content);
                    }, function(xhr, status, error) {
                        // Upon failure... set the tooltip content to error
                        api.set('content.text', status + ': ' + error);
                    });
        
                    return 'Loading...'; // Set some initial text
                }
            },
            position: {
                viewport: $(window)
            },
            style: 'qtip-user'
         });
     });
 });
</script>
</body>
</html>
