<?php
function main ($context)
{
    $cdn = $context->app->config->web('cdn');
?>
<html>
<head>
<meta name="Generated" content="<?php echo date(DATE_RFC2822) ?>">
<meta name="D" content="D is for lots of things"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<style type="text/css" media="screen">@import "<?php echo $cdn ?>/css/scanner_download.css";</style>
<style>
.holder { margin: 10px; }
</style>
<title>Scanner</title>
</head>
<body>
<script type="text/javascript">

$(document).ready
(
    function() 
    {
    }
);
</script>
<div id="container">
  <div id="copy">
    <h1>"ROCK THIS" MUSIC Scanner Desktop App</h1>
    <p>With the ROCK THIS desktop music scanner you can scan your exisiting music libraries and find music you already own which is available for ROCK THIS games. If the scanner finds music you own on your drive, it will unlock the songs and allow you to use them within ROCK THIS games for free! </p>
    <ol>
      <li>Easily scan your hard drive.</li>
      <li>Scan your computer any time you want.</li>
      <li>Works with Mac or Windows.</li>
    </ol>
    <h2>Get <a href="http://get.adobe.com/air" target="_blank">ADOBE AIR</a> then get the <a href="<?php echo $cdn ?>/app/GigItScanner.air?<?php echo microtime(true) ?>" download>ROCK THIS SCANNER</a>.</h2>
    <p><a href="https://apps.facebook.com/clickr_dev/">Return to ROCK THIS</a></p>
  </div>
</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47310144-1', 'facebook.com');
  ga('send', 'pageview');
</script>
</body>
</html>
<?php
}
main ($this);
?>
