<!DOCTYPE html>
<html>
 <head prefix=
    "og: http://ogp.me/ns#
     fb: http://ogp.me/ns/fb# 
     product: http://ogp.me/ns/product#">
	<meta property="fb:app_id" content="239795399531047" />
	<meta property="og:video"            content="https://gigitmediaprod.s3.amazonaws.com/Support/facebookVID.mp4"> 
	<meta property="og:video:type"       content="video/mp4"> 
	<meta property="og:video:width"      content="400"> 
	<meta property="og:video:height"     content="225">
	<meta property="og:title" content="CAN YOU GIGIT?" />
	<meta property="og:type" content="object" />
	<meta property="og:url" content="https://clickr1.droolpot.com/hub/share/" />
	<meta property="og:image" content="https://gigitmediaprod.s3.amazonaws.com/Support/GIG-IT2.jpg" />
	<meta property="og:image:width"  content="50">
	<meta property="og:image:height" content="50">
	<meta property="og:site_name" content="wt"/>
	<meta property="og:description" content="I just created a slamming concert on GIG-IT, check it out! Will I sell-out? Watch-it, Like-it and Share-it, so that I can level up!" />
  </head>
<script>
top.location.href = "https://apps.facebook.com/clickr_dev/";
</script>
</html>
